spring.application.name=backend-core

# Configuración del Servidor Web
server.port=8080

# Configuración de la Base de Datos H2 (En Memoria)
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Muestra los queries SQL en la consola para ver qué está pasando por debajo
spring.jpa.show-sql=true
# Permite que H2 cree las tablas automáticamente basándose en nuestras clases Java
spring.h2.console.enabled=true

# Configuración de RabbitMQ (El Broker de Mensajería)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Fuerza a que la mensajería use serialización JSON por defecto
spring.mvc.converters.preferred-json-mapper=jackson

# Configuración del nombre de la cola que usaremos
app.rabbitmq.queue=cola.notificaciones