spring.application.name=backend-worker

# Configuración del Servidor Web (Cambiamos el puerto para que no choque con el Core)
server.port=8081

# Configuración de RabbitMQ (Apuntamos al mismo Docker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Permitir la deserialización de clases del JDK comunes (como java.time) y de tus propios paquetes
spring.amqp.deserialization.allowed.list=java.util.*,java.lang.*,java.time.*,com.ejercicio.backendworker.model.*

spring.amqp.deserialization.trust.all=true

# Nombre de la cola que el Worker se quedará escuchando
app.rabbitmq.queue=cola.notificaciones